# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Diaconesq
tagline:          'Live & learn'
description:      'Live & <em>learn</em>'
url:              http://blog.diaconesq.ro
baseurl:          /

author:
  name:           'Cristian Diaconescu'
  url:            https://twitter.com/diaconescu

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
