# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Diaconesq
tagline:          'Learn & let learn'
description:      'Learn & <em>let learn</em>'
url:              http://blog.diaconesq.ro
baseurl:          /

future: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

author:
  name:           'Cristian Diaconescu'
  url:            https://twitter.com/diaconescu

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
